language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install pep8 pyflakes --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - "pyflakes mailpile"
  - "pep8 mailpile"
  - "scripts/mailpile-test.py"

