# SPDX-FileCopyrightText: 2011-2015  Bjarni R. Einarsson, Mailpile ehf and friends
# SPDX-License-Identifier: AGPL-3.0-or-later

language: python
python: 2.7
env:
  - TOX_ENV=py27

addons:
  apt:
    packages:
      - gnupg

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
