# SPDX-FileCopyrightText: 2011-2015  Bjarni R. Einarsson, Mailpile ehf and friends
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.0'
services:
  mailpile:
    container_name: mailpile
    build: .
    image: mailpile
    volumes:
      - .:/Mailpile
      - .dev-mailpile-data:/mailpile-data
    ports:
      - 33411:33411

